### ISSUE TITLE
Stuck jobs in enqueue

### ISSUE THREAD

**Issue by hwhelchel** [deanpcmad/sidekiq-limit_fetch#103]
Been using the gem without problems in a simple setup. On heroku standard dynos. 1 dyno worker. 1 Heroku Redis instance that supports up to 40 connections.

```ruby
require 'sidekiq'

Sidekiq.configure_client do |config|
  config.redis = { size: 1 }
end

Sidekiq.configure_server do |config|
  # The config.redis is calculated by the
  # concurrency value so you do not need to
  # specify this. For this demo I do
  # show it to understand the numbers
  config.redis = { size: 35 }
end
```

```yaml
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 33

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - default
  - mailers
  - memory_mailers
  - memory_priority
  - memory
blocking:
  - memory_mailers
  - memory_priority

:limits:
  memory_mailers: 1
  memory_priority: 2
  memory: 1

# you can override concurrency based on environment
production: &production
  :concurrency: 33

demo:
  <<: *production
```
Occasionally I have a large memory intensive task to run so I spin up 8 standard worker dynos. In this scenario I have

```ruby
require 'sidekiq'

Sidekiq.configure_client do |config|
  config.redis = { size: 1 }
end

Sidekiq.configure_server do |config|
  # The config.redis is calculated by the
  # concurrency value so you do not need to
  # specify this. For this demo I do
  # show it to understand the numbers
  config.redis = { size: 4 }
end
```
```yaml
# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 2

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - default
  - mailers
  - memory_mailers
  - memory_priority
  - memory
blocking:
  - memory_mailers
  - memory_priority

:limits:
  memory_mailers: 8
  memory_priority: 16
  memory: 8

:process_limits:
  memory_mailers: 1
  memory_priority: 2
  memory: 1

# you can override concurrency based on environment
production: &production
  :concurrency: 2

demo:
  <<: *production
```

When I scale up to 8 workers, jobs get stuck in enqueue for the `memory_priority` queue when I redeploy the code. Maybe in other scenarios too. To date the only way I've found to fix it is to `Redis.new.flushall` and re-enqueue the jobs that need to be run.

Appreciate your help @brainopia
