### ISSUE TITLE
Limits not being picked up from sidekiq.yml file?

### ISSUE THREAD

**Issue by henry74** [deanpcmad/sidekiq-limit_fetch#15]
Here's my yaml file:

``` yml
:verbose: false
:concurrency: 4
:queues: 
  - soprano
  - sphinx4
:limits:
  soprano: 1
  sphinx4: 1
```

I have purposely set it to limit to 1 worker just to test.  When I queue jobs for either soprano or sphinx4 they use all available workers up to 4.  What am I missing here?
